name: lokraven
favicon: null
layout_spectrum: 0.73339
typography_spectrum: 0.24495
title: The Black Birdie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08090b'
    - '#71a7ed'
    - '#76726f'
    - '#433e3b'
    - '#e5dfdb'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
