name: lokraven
favicon: null
layout_spectrum: 0.2701
typography_spectrum: 0.24495
title: The Black Birdie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08090b'
    - '#71a7ed'
    - '#76726f'
    - '#433e3b'
    - '#e5dfdb'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
