name: lokraven
favicon: null
layout_spectrum: 0.73316
typography_spectrum: 0.24495
title: The Black Birdie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3e1e2'
    - '#75a1c4'
    - '#5980b7'
    - '#232321'
    - '#38546c'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
