name: lokraven
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24495
title: The Black Birdie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e6eb'
    - '#899cc6'
    - '#546da5'
    - '#a0b0ad'
    - '#ccc6c8'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
